FROM fixel/zeek-cluster:arm64v8-zeek-ssh-node

COPY config/node.cfg /bro/etc/node.cfg
COPY config/networks.cfg /bro/etc/networks.cfg
COPY config/init_cluster_broctl.sh /bro/etc/cluster_config/start-command.sh
RUN chmod a+x /bro/etc/cluster_config/start-command.sh

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord","-c","/etc/supervisor/supervisord.conf"]
